### ISSUE TITLE
Приветствую! Хотелось бы задать пару вопросов.

### ISSUE THREAD

**Issue by 2010Bronks** [Legionidk/GOD-SYSTEM-Lua#1]
Во-первых, хотел бы выразить огромную благодарность за твою работу!
Это довольно крупный проект с хорошим и нужным функционалом.

Во-вторых, хотелось бы узнать как можно было бы связаться с тобой. Если не хочется показывать свои данные, то можно написать мне на форуме миднайт (Bronks) или в дискорде (bronks).
Хотелось бы обсудить некоторые вещи!

**Comment by Legionidk** [comment]
😐
Отпишу в дискорд!
